packages:
  - "web"
  - "contracts"
allowBuilds:
  '@prisma/client': true
  esbuild: true
  '@prisma/engines': true
  bufferutil: true
  keccak: true
  prisma: true
  unrs-resolver: true
  secp256k1: true
  utf-8-validate: true
